apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher
  namespace: default
secrets:
- name: pod-watcher-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cnsbench-pod-watcher
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnsbench-binding
subjects:
  - kind: ServiceAccount
    name: pod-watcher
    namespace: default
roleRef:
  kind: ClusterRole
  name: cnsbench-pod-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: pod-watcher-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: pod-watcher
type: kubernetes.io/service-account-token
