apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: benchmarktestings.benchmarking.example.com
spec:
  group: benchmarking.example.com
  names:
    kind: BenchmarkTesting
    listKind: BenchmarkTestingList
    plural: benchmarktestings
    singular: benchmarktesting
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BenchmarkTesting is the Schema for the benchmarktestings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BenchmarkTestingSpec defines the desired state of BenchmarkTesting
          properties:
            controlOpUnits:
              items:
                properties:
                  interval:
                    description: Time between control ops in seconds
                    minimum: 0
                    type: integer
                  provisionOpArgs:
                    properties:
                      size:
                        type: string
                    required:
                    - size
                    type: object
                  snapshotOpArgs:
                    properties:
                      snapshotClass:
                        type: string
                      target:
                        type: string
                    required:
                    - snapshotClass
                    - target
                    type: object
                  startDelay:
                    description: Time in seconds to delay the start of the control
                      operations.
                    type: integer
                  type:
                    enum:
                    - snapshot
                    - provision
                    - reschedule
                    type: string
                required:
                - interval
                - type
                type: object
              type: array
            ioOpUnits:
              items:
                properties:
                  appCmdline:
                    description: Command line
                    type: string
                  configName:
                    description: Name of ConfigMap for IOU config
                    type: string
                  image:
                    description: Name of container image to run, defaults to benchmarking/fio:3.18-8
                    type: string
                  outputDir:
                    type: string
                  outputParser:
                    description: Name of ConfigMap for script
                    type: string
                  parserCmdline:
                    description: Command line
                    type: string
                  parserImage:
                    description: Defaults to ubuntu:latest
                    type: string
                  pvcName:
                    description: Name of PVC to use, if not specified creates a new
                      PVC from the storage controller specified in BenchmarkTesting
                      CR
                    type: string
                  workingDir:
                    description: "WorkingDir specifies directory inside the container
                      where the PV should be mounted. \n OutputDir specifies the directory
                      inside the container where the output generated by the testing
                      application should be output - this is where the emptyDir is
                      attached so the controller can collect the output after the
                      test completes. \n The testing application's configuration should
                      match these directories: e.g. an fio config should set \"directory\"
                      to be the same as WorkingDir and write_bw_log should be set
                      to a file under OutputDir"
                    type: string
                required:
                - appCmdline
                - configName
                - outputDir
                - outputParser
                - parserCmdline
                - workingDir
                type: object
              type: array
            storageClass:
              description: Name of storage class from which PVs are provisioned.  If
                not set, each IOU needs to specify which PVC to use.
              type: string
          type: object
        status:
          description: BenchmarkTestingStatus defines the observed state of BenchmarkTesting
          properties:
            podNames:
              items:
                type: string
              type: array
          required:
          - podNames
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
