apiVersion: cnsbench.example.com/v1alpha1
kind: Benchmark
metadata:
  name: example-benchmark
spec:
  runtime: 120
  actions:
    - scaleSpec:
        name: sample-deployment
        rateName: rateOne
  rates:
    - name: rateOne
      constantIncreaseDecreaseRateSpec:
        incInterval: 30
        decInterval: 10
        min: 1
        max: 5
      #constantRateSpec:
      #  interval: 5
