apiVersion: v1
kind: Namespace
metadata:
  name: library
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
data:
  pvc.yaml: |
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: vol-{{ACTION_NAME}}-{{INSTANCE_NUM}}
      namespace: default
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{storageClass}}
      resources:
        requests:
          storage: 5Gi
  workload.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: fb-{{ACTION_NAME}}-{{INSTANCE_NUM}}
      namespace: default
      annotations:
        sync: "1"
        role: workload
        outputFile: /output/output
        parser: null-parser
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: cnsbench/filebench:latest
            imagePullPolicy: IfNotPresent
            name: filebench
            command: ["sh", "-c", "filebench -f /usr/local/share/filebench/workloads/{{workload}}.f | tee /output/output"]
            volumeMounts:
              - mountPath: /var/data/
                name: data
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: {{volname}}
kind: ConfigMap
metadata:
  annotations:
    cnsbench.default.storageClass: local-storage
    cnsbench.default.volname: vol-{{ACTION_NAME}}-{{INSTANCE_NUM}}
    cnsbench.default.workload: mongo
  labels:
    type: workload
  name: quickstart-filebench
  namespace: library
---
apiVersion: v1
data:
  parser.sh: |
    #!/bin/sh

    cat $1
    exit 0
kind: ConfigMap
metadata:
  annotations:
    container: dwdraju/alpine-curl-jq
  labels:
    type: parser
  name: null-parser
  namespace: library
