apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnsbench
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cnsbench
  template:
    metadata:
      labels:
        name: cnsbench
    spec:
      serviceAccountName: cnsbench
      containers:
        - name: cnsbench
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - cnsbench
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cnsbench"
