apiVersion: cnsbench.example.com/v1alpha1
kind: Benchmark
metadata:
  name: quickstart-benchmark
spec:
  workloads:
    - name: quickstart
      workload: quickstart-filebench
      outputFiles:
      - filename: /output/output
        parser: null-parser
        target: workload
        sink: es
      vars:
        storageClass: local-storage
  outputs:
    - name: es
      httpPostSpec:
        url: http://cnsbench-output-collector.cnsbench-system.svc.cluster.local:8888/ex1
