apiVersion: cnsbench.example.com/v1alpha1
kind: Benchmark
metadata:
  name: quickstart-benchmark
spec:
  workloads:
    - name: quickstart
      workload: fio
      outputFiles:
      - filename: /output/output.json
        parser: basic-parser
        target: workload
        sink: es
      vars:
        storageClass: local-storage
        fiosize: 500Mi
        pvcsize: 1Gi
  outputs:
    - name: es
      httpPostSpec:
        url: http://cnsbench-output-collector.cnsbench-system.svc.cluster.local:8888/ex1
