apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: sample
        image: busybox
        command: ["sleep", "30"]
      restartPolicy: Never
