apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snapshot-test
  namespace: default
spec:
  volumeSnapshotClassName: openebs-snapshotclass
  source:
    persistentVolumeClaimName: freenas-claim1
